# Generated by Django 3.1.1 on 2020-09-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='front_page',
            field=models.BooleanField(default=False, help_text='If enabled, this package will display on the homepage.'),
        ),
    ]
