# Generated by Django 3.1.1 on 2020-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20200916_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
