# Generated by Django 3.1.1 on 2020-09-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_organisation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
