# Generated by Django 3.1.1 on 2020-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_organisation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='about',
            field=models.TextField(help_text='The contents of this field will display on the about page.', null=True),
        ),
    ]
