# Generated by Django 3.1.1 on 2020-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_organisation_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='privacy',
            field=models.TextField(help_text='The contents of this field will display on the privacy page.', null=True),
        ),
    ]
