# Generated by Django 3.1.1 on 2020-09-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_organisation_privacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banding',
            options={'ordering': ('price', 'name')},
        ),
        migrations.AddField(
            model_name='signup',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='signup.package'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
