# Generated by Django 3.1.1 on 2020-09-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20200921_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
