# Generated by Django 3.1.1 on 2020-09-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_auto_20200923_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Enter the full account url eg. https://twitter.com/openlibhums', max_length=100, null=True),
        ),
    ]
