# Generated by Django 3.1.1 on 2020-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_notification_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmanager',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=255),
            preserve_default=False,
        ),
    ]
