# Generated by Django 3.1.1 on 2020-10-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_billingmanager_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmanager',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Leave blank to be notified of all sign ups.', null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.country'),
        ),
    ]
