# Generated by Django 3.1.1 on 2020-10-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0013_auto_20201018_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email_address',
            field=models.EmailField(max_length=200),
        ),
    ]
