# Generated by Django 3.1.1 on 2020-11-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0014_auto_20201018_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='display_faq',
            field=models.BooleanField(default=False, help_text='If enabled the FAQ page will display.'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='display_resources',
            field=models.BooleanField(default=False, help_text='If enabled the Resources page will display.'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='faq',
            field=models.TextField(blank=True, help_text='If the Display FAQ setting is enabled this page will display in the nav and site.', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='resources',
            field=models.TextField(blank=True, help_text='If the Display Resources setting is enabled this page will display in the nav and site.', null=True),
        ),
    ]
