# Generated by Django 3.1.1 on 2020-11-30 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0018_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke')], max_length=10)),
                ('date_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_range', models.TextField(blank=True, null=True)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup')),
            ],
            options={
                'ordering': ('-date_stamp',),
            },
        ),
    ]
