# Generated by Django 3.1.1 on 2020-12-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0020_accesslog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='domain',
            field=models.CharField(default='localhost', help_text='The domain for this organisation', max_length=300),
        ),
    ]
