# Generated by Django 3.1.1 on 2020-12-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0021_organisation_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='banding',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.organisation'),
        ),
        migrations.AddField(
            model_name='billingmanager',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.organisation'),
        ),
        migrations.AddField(
            model_name='package',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.organisation'),
        ),
    ]
