# Generated by Django 3.1.1 on 2020-12-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0023_accesslogexportcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslogexportcode',
            options={'ordering': ('-active',)},
        ),
        migrations.AddField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
