# Generated by Django 3.1.1 on 2020-12-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0026_accesslog_payment_handler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter Billing Managers full name.', max_length=300)),
                ('email', models.EmailField(max_length=255)),
                ('contact_type', models.CharField(choices=[('billing', 'Billing'), ('access', 'Access')], default='billing', max_length=20)),
                ('country', models.ForeignKey(blank=True, help_text='Leave blank to be notified of all sign ups.', null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.country')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.organisation')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='BillingManager',
        ),
    ]
