# Generated by Django 3.1.1 on 2020-12-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0027_auto_20201210_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='access_manager_message',
            field=models.TextField(default="{{organisation.name}}'s access controls have been updated.", help_text='Message send to Access Managers when access is changed.'),
        ),
    ]
