# Generated by Django 3.1.1 on 2020-12-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0028_organisation_access_manager_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslogexportcode',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signup.organisation'),
        ),
    ]
