# Generated by Django 3.1.1 on 2020-09-21 09:27

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        from install.countries import COUNTRY_CHOICES
        Country = apps.get_model("signup", "Country")
        db_alias = schema_editor.connection.alias

        for choice in COUNTRY_CHOICES:
            Country.objects.using(db_alias).get_or_create(
                code=choice[0],
                name=choice[1],
            )

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]