# Generated by Django 3.1.1 on 2020-09-21 09:27

from __future__ import unicode_literals

from django.db import migrations

institution_message = """<p>Thank you for your signup to {{ package.name }}. We will be in touch in the near future with the next steps.</p>
<p>Yours,</p>
<p>{{ organisation.name }}</p>
"""
billing_manager_message = """<p>A new signup has been made to {{ package.name }}, from {{ signup.institution }} for {{ banding.price }}{{ banding.currency }}. Please <a href=\"{{ PRIMARY_BASE_DOMAIN }}admin/signup/signup/\">click here</a> to view the details.</p>
<p>Yours,</p>
<p>{{ organisation.name }}</p>
"""

class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Organisation = apps.get_model("signup", "Organisation")

        for org in Organisation.objects.all():
            org.billing_manager_message = billing_manager_message
            org.institution_message = institution_message
            org.save()

    dependencies = [
        ('install', '0001_initial'),
        ('signup', '0011_notification_emails'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
